- hosts: 'vulcan-k8s-master-1 '
  become: yes
  tasks:
    - name: change docker driver     
      shell: |
          cat <<EOF | sudo tee /etc/docker/daemon.json
            {"exec-opts": ["native.cgroupdriver=systemd"],"log-driver": "json-file","log-opts": {"max-size": 
"100m"},"storage-driver": "overlay2"}
            EOF

    - name: update and reset the changes
      shell: |
            sudo systemctl daemon-reload
            sudo systemctl restart docker
            sudo kubeadm reset -f    
               
    - name: initialize the cluster
      shell: sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --kubernetes-version 1.22.0
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: for accessing kubectl
      shell: |
            mkdir -p $HOME/.kube
            sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config 

    - name: install Pod network
      become: yes
      become_user: kube
      shell: sudo kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
      args:
        chdir: $HOME
        
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: kube
      shell: sudo kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" 
dest="/tmp/kubernetes_join_command" mode=0777
