"""FLASK CONFIGURATIONS"""

GRPC_SERVER = 'localhost'
GRPC_SERVER_PORT = '9090' 
KAFKA_SERVER = 'localhost'
KAFKA_SERVER_PORT = '9092'
KAFKA_INGESTOR_TOPIC = 'ingestor'
KAFKA_STORM_DETECTION_TOPIC = 'storm-clustering'
