# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ingestor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ingestor.proto',
  package='com.WeatherForcast.DbMgmtService.grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eingestor.proto\x12%com.WeatherForcast.DbMgmtService.grpc\"_\n\x06msgUrl\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05month\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\t\x12\x0f\n\x07station\x18\x04 \x01(\t\x12\x0c\n\x04time\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\"\x13\n\x05msgId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xde\x01\n\rDbMgmtService\x12\x66\n\x07saveurl\x12-.com.WeatherForcast.DbMgmtService.grpc.msgUrl\x1a,.com.WeatherForcast.DbMgmtService.grpc.msgId\x12\x65\n\x06geturl\x12,.com.WeatherForcast.DbMgmtService.grpc.msgId\x1a-.com.WeatherForcast.DbMgmtService.grpc.msgUrlb\x06proto3'
)




_MSGURL = _descriptor.Descriptor(
  name='msgUrl',
  full_name='com.WeatherForcast.DbMgmtService.grpc.msgUrl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='com.WeatherForcast.DbMgmtService.grpc.msgUrl.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='month', full_name='com.WeatherForcast.DbMgmtService.grpc.msgUrl.month', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='year', full_name='com.WeatherForcast.DbMgmtService.grpc.msgUrl.year', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='station', full_name='com.WeatherForcast.DbMgmtService.grpc.msgUrl.station', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='com.WeatherForcast.DbMgmtService.grpc.msgUrl.time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='com.WeatherForcast.DbMgmtService.grpc.msgUrl.url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=152,
)


_MSGID = _descriptor.Descriptor(
  name='msgId',
  full_name='com.WeatherForcast.DbMgmtService.grpc.msgId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.WeatherForcast.DbMgmtService.grpc.msgId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['msgUrl'] = _MSGURL
DESCRIPTOR.message_types_by_name['msgId'] = _MSGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgUrl = _reflection.GeneratedProtocolMessageType('msgUrl', (_message.Message,), {
  'DESCRIPTOR' : _MSGURL,
  '__module__' : 'ingestor_pb2'
  # @@protoc_insertion_point(class_scope:com.WeatherForcast.DbMgmtService.grpc.msgUrl)
  })
_sym_db.RegisterMessage(msgUrl)

msgId = _reflection.GeneratedProtocolMessageType('msgId', (_message.Message,), {
  'DESCRIPTOR' : _MSGID,
  '__module__' : 'ingestor_pb2'
  # @@protoc_insertion_point(class_scope:com.WeatherForcast.DbMgmtService.grpc.msgId)
  })
_sym_db.RegisterMessage(msgId)



_DBMGMTSERVICE = _descriptor.ServiceDescriptor(
  name='DbMgmtService',
  full_name='com.WeatherForcast.DbMgmtService.grpc.DbMgmtService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=176,
  serialized_end=398,
  methods=[
  _descriptor.MethodDescriptor(
    name='saveurl',
    full_name='com.WeatherForcast.DbMgmtService.grpc.DbMgmtService.saveurl',
    index=0,
    containing_service=None,
    input_type=_MSGURL,
    output_type=_MSGID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='geturl',
    full_name='com.WeatherForcast.DbMgmtService.grpc.DbMgmtService.geturl',
    index=1,
    containing_service=None,
    input_type=_MSGID,
    output_type=_MSGURL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DBMGMTSERVICE)

DESCRIPTOR.services_by_name['DbMgmtService'] = _DBMGMTSERVICE

# @@protoc_insertion_point(module_scope)
