# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ingestor_pb2 as ingestor__pb2


class DbMgmtServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.saveurl = channel.unary_unary(
                '/com.WeatherForcast.DbMgmtService.grpc.DbMgmtService/saveurl',
                request_serializer=ingestor__pb2.msgUrl.SerializeToString,
                response_deserializer=ingestor__pb2.msgId.FromString,
                )
        self.geturl = channel.unary_unary(
                '/com.WeatherForcast.DbMgmtService.grpc.DbMgmtService/geturl',
                request_serializer=ingestor__pb2.msgId.SerializeToString,
                response_deserializer=ingestor__pb2.msgUrl.FromString,
                )


class DbMgmtServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def saveurl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def geturl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DbMgmtServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'saveurl': grpc.unary_unary_rpc_method_handler(
                    servicer.saveurl,
                    request_deserializer=ingestor__pb2.msgUrl.FromString,
                    response_serializer=ingestor__pb2.msgId.SerializeToString,
            ),
            'geturl': grpc.unary_unary_rpc_method_handler(
                    servicer.geturl,
                    request_deserializer=ingestor__pb2.msgId.FromString,
                    response_serializer=ingestor__pb2.msgUrl.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.WeatherForcast.DbMgmtService.grpc.DbMgmtService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DbMgmtService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def saveurl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.WeatherForcast.DbMgmtService.grpc.DbMgmtService/saveurl',
            ingestor__pb2.msgUrl.SerializeToString,
            ingestor__pb2.msgId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def geturl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.WeatherForcast.DbMgmtService.grpc.DbMgmtService/geturl',
            ingestor__pb2.msgId.SerializeToString,
            ingestor__pb2.msgUrl.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
